export const ENV_VARIABLES = {
  GCP_SERVICE_ACCOUNT_B64: "GCP_SERVICE_ACCOUNT_B64",
  REDIS_DB_PASSWORD: "REDIS_DB_PASSWORD",
  REDIS_DB_USERNAME: "REDIS_DB_USERNAME",
  REDIS_DB_HOST: "REDIS_DB_HOST",
  REDIS_DB_PORT: "REDIS_DB_PORT",
  MONGO_DB_NAME: "MONGO_DB_NAME",
  MONGO_USERNAME: "MONGO_USERNAME",
  MONGO_PASSWORD: "MONGO_PASSWORD",
  JWT_SECRET: "JWT_SECRET",
  PHOTON_TRACKING_APP_BASE_URL: "PHOTON_TRACKING_APP_BASE_URL",
  PHOTON_SELECT_APP_BASE_URL: "PHOTON_SELECT_APP_BASE_URL",
  MERCHANT_DATABASE_PREFIX: "MERCHANT_DATABASE_PREFIX",
  MAILGUN_API_KEY: "MAILGUN_API_KEY",
  MAILGUN_DOMAIN: "MAILGUN_DOMAIN",
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET",
  PIXELSETU_SECRET_SALT: "PIXELSETU_SECRET_SALT",
  SECRET_ENCRYPTION_KEY: "SECRET_ENCRYPTION_KEY",
  HOST: "HOST" //API Hosted BASE URL, e.g. https://auth.pixelsetu.com
} as const;

export function env(variableName: keyof typeof ENV_VARIABLES) {
  const value = process.env[`${variableName}`];
  if (!value) {
    throw new Error(`Environment Variable Missing: ${variableName}`);
  }
  return value;
}
