name: 🚀 Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PIXELSETUTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PIXELSETUTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PIXELSETUTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      # ✅ FIXED LOGIN
      - name: Login to ACR
        run: az acr login --name pixelsetuacr

      - name: Build Image
        run: |
          docker build \
            -t pixelsetuacr.azurecr.io/pixelsetu-auth-svc:${{ env.SHORT_SHA }} \
            -t pixelsetuacr.azurecr.io/pixelsetu-auth-svc:latest \
            .
      - name: Push Image
        run: |
          docker push pixelsetuacr.azurecr.io/pixelsetu-auth-svc:${{ env.SHORT_SHA }}
          docker push pixelsetuacr.azurecr.io/pixelsetu-auth-svc:latest
      - name: Deploy
        run: |
          az containerapp update \
            --name pixelsetu-auth-svc \
            --resource-group Pixelsetu \
            --image pixelsetuacr.azurecr.io/pixelsetu-auth-svc:${{ env.SHORT_SHA }}