name: 🚀 Deploy to Azure Container Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/pixelsetu-auth-svc:${{ env.SHORT_SHA }} \
            -t ghcr.io/${{ github.repository_owner }}/pixelsetu-auth-svc:latest \
            .

      - name: Push Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/pixelsetu-auth-svc:${{ env.SHORT_SHA }}
          docker push ghcr.io/${{ github.repository_owner }}/pixelsetu-auth-svc:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PIXELSETUAUTH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PIXELSETUAUTH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PIXELSETUAUTH_AZURE_SUBSCRIPTION_ID }}

      - name: Set Registry Credentials
        run: |
          az containerapp registry set \
            --name pixelsetu-auth-svc \
            --resource-group Pixelsetu \
            --server ghcr.io \
            --username ${{ github.repository_owner }} \
            --password ${{ secrets.GHCR_PAT }}

      - name: Deploy
        run: |
          az containerapp update \
            --name pixelsetu-auth-svc \
            --resource-group Pixelsetu \
            --image ghcr.io/${{ github.repository_owner }}/pixelsetu-auth-svc:${{ env.SHORT_SHA }}
